version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./test_clickhouse:/var/lib/clickhouse
      - ./test_ch_config.xml:/etc/clickhouse-server/config.d/test_ch_config.xml
      - ./test_backups:/backups
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
